default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  adapter: postgresql
  database: contur_customers_dev
  username: rails_dev
  password: aqwe123
  encoding: unicode
  pool: 10
  timeout: 10000

test:
  adapter: postgresql
  database: contur_customers_test
  username: rails_dev
  password: aqwe123
  encoding: unicode
  pool: 10
  timeout: 10000

production:
  <<: *default
  database: collabfield_production
  username: collabfield
  password: <%= ENV['COLLABFIELD_DATABASE_PASSWORD'] %>
